### ISSUE TITLE
Refactor to use Provider

### ISSUE THREAD

**Issue by jeremytowne** [yuetlong/skillsoft-technical-exercise#1]
Suggest refactoring the main app to use a `Provider` and the `useQuery` hook. See https://www.apollographql.com/docs/react/get-started/#connect-your-client-to-react

**Comment by yuetlong** [comment]
Resolved in https://github.com/yuetlong/skillsoft-technical-exercise/commit/8719fdabb14da43a91dedcf3786851928c883de7
