### ISSUE TITLE
Remove react state

### ISSUE THREAD

**Issue by jeremytowne** [yuetlong/skillsoft-technical-exercise#2]
Remove react state from https://github.com/yuetlong/skillsoft-technical-exercise/blob/main/src/App.js#L13 and refactor to use apollo's `loadMore` functionality. https://www.apollographql.com/docs/react/pagination/core-api/

**Comment by yuetlong** [comment]
Resolved in https://github.com/yuetlong/skillsoft-technical-exercise/commit/8719fdabb14da43a91dedcf3786851928c883de7
